# Generated by Django 5.1.1 on 2024-09-29 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('procent', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('geocoord', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.clientstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('acceptdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('planamount', models.FloatField()),
                ('plansum', models.FloatField()),
                ('amount', models.FloatField()),
                ('sum', models.FloatField()),
                ('supplysum', models.FloatField()),
                ('total', models.FloatField()),
                ('workerpercent', models.IntegerField()),
                ('workersum', models.FloatField()),
                ('profitsum', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_order', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.client')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_order', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.priority')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.state')),
            ],
        ),
    ]
